# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: HNN.Bisnor
PackageVersion: 5.1.5
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /NORESTART /SUPPRESSMSGBOXES
  SilentWithProgress: /SILENT /NORESTART /SUPPRESSMSGBOXES
UpgradeBehavior: install
ProductCode: '{E1D4A738-4F92-4C61-9E2F-068DF14D9842}_is1'
AppsAndFeaturesEntries:
- DisplayName: Bisnor
  Publisher: HNN
  DisplayVersion: 5.1.5
  ProductCode: '{E1D4A738-4F92-4C61-9E2F-068DF14D9842}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nikan48g/Bisnor/releases/download/v5.1.5/Bisnor-5.1.5-win-x64.exe
  InstallerSha256: 6951EB951D7185E8CE9DE5C9CDA1A6B8072053D52ECBC983350AD3C0C7F0978E
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2026-10-09
